= class Saga

Defines a long-running business process that coordinates across events and time.

Sagas implement the Saga pattern for managing complex workflows that span multiple aggregates, external services, and time-based operations. They provide stateful event processing with support for timers, error handling, and process coordination.

 TimeoutNames - Union type of timer names this saga can schedule  InstanceData - Type of the saga's persistent state data

Key Features: - \*\*Stateful Processing\*\*: Maintains state across multiple events - \*\*Timer Support\*\*: Schedule delays and recurring operations - \*\*Error Handling\*\*: Custom error handling and compensation logic - \*\*Event Correlation\*\*: Match events to specific saga instances - \*\*Parallel Processing\*\*: Configurable concurrency for high throughput



== Properties

[id="eventicle_eventiclejs_Saga_errorHandler_member"]
=== errorHandler

========






.Signature
[source,typescript]
----
errorHandler: (saga: any, event: EventicleEvent, error: Error) => Promise<void>;
----

========
[id="eventicle_eventiclejs_Saga_eventHandler_member"]
=== eventHandler

========






.Signature
[source,typescript]
----
eventHandler: Map<string, {
        config: HandlerConfig<any, InstanceData, TimeoutNames>;
        handle: (saga: SagaInstance<TimeoutNames, InstanceData>, event: EventicleEvent) => Promise<void>;
    }>;
----

========
[id="eventicle_eventiclejs_Saga_name_member"]
=== name

========






.Signature
[source,typescript]
----
readonly name: string;
----

========
[id="eventicle_eventiclejs_Saga_parallelEventCount_member"]
=== parallelEventCount

========






.Signature
[source,typescript]
----
parallelEventCount: number;
----

========
[id="eventicle_eventiclejs_Saga_starts_member"]
=== starts

========






.Signature
[source,typescript]
----
starts: Map<string, {
        config: StartHandlerConfig<any, InstanceData, TimeoutNames>;
        handle: (saga: SagaInstance<TimeoutNames, InstanceData>, event: EventicleEvent) => Promise<void>;
    }>;
----

========
[id="eventicle_eventiclejs_Saga_streams_member"]
=== streams

========






.Signature
[source,typescript]
----
streams: string[];
----

========
[id="eventicle_eventiclejs_Saga_streamSubs_member"]
=== streamSubs

========






.Signature
[source,typescript]
----
streamSubs: EventSubscriptionControl[];
----

========
[id="eventicle_eventiclejs_Saga_timerHandler_member"]
=== timerHandler

========






.Signature
[source,typescript]
----
timerHandler: Map<TimeoutNames, {
        handle: (saga: SagaInstance<TimeoutNames, InstanceData>) => Promise<void>;
    }>;
----

========

== Constructors

[id="eventicle_eventiclejs_Saga_constructor_1"]
=== (constructor)(name)

========

Constructs a new instance of the `Saga` class



.Parameters
[%header,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|name
m|string
|
|===

.Signature
[source,typescript]
----
constructor(name: string);
----

========

== Methods

[id="eventicle_eventiclejs_Saga_on_member_1"]
=== on(eventName, config, handler)

========

Registers an event handler for existing saga instances.

When the specified event type is received, the handler will be called on any existing saga instances that match the event based on the matchInstance configuration.



.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|eventName
m|string
|The event type to handle

m|config
m|\~HandlerConfig&lt;T, InstanceData, TimeoutNames&gt;
|Configuration for instance matching and locking

m|handler
m|(saga: xref:eventicle_eventiclejs_SagaInstance_class.adoc[SagaInstance]&lt;TimeoutNames, InstanceData&gt;, event: T) =&gt; Promise&lt;void&gt;
|The function to execute for matching instances

s|Returns
m|xref:eventicle_eventiclejs_Saga_class.adoc[Saga]&lt;TimeoutNames, InstanceData&gt;
|
|===

.Signature
[source,typescript]
----
on<T extends EventicleEvent>(eventName: string, config: HandlerConfig<T, InstanceData, TimeoutNames>, handler: (saga: SagaInstance<TimeoutNames, InstanceData>, event: T) => Promise<void>): Saga<TimeoutNames, InstanceData>;
----

========
[id="eventicle_eventiclejs_Saga_onError_member_1"]
=== onError(handler)

========





.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|handler
m|(saga: any, event: xref:eventicle_eventiclejs_EventicleEvent_interface.adoc[EventicleEvent], error: Error) =&gt; Promise&lt;void&gt;
|

s|Returns
m|xref:eventicle_eventiclejs_Saga_class.adoc[Saga]&lt;TimeoutNames, InstanceData&gt;
|
|===

.Signature
[source,typescript]
----
onError(handler: (saga: any, event: EventicleEvent, error: Error) => Promise<void>): Saga<TimeoutNames, InstanceData>;
----

========
[id="eventicle_eventiclejs_Saga_onTimer_member_1"]
=== onTimer(name, handle)

========

Register a handler for a timer triggered saga step.

This will be called on the timer.

No event is present.



.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|name
m|TimeoutNames
|The name of the timer

m|handle
m|(saga: xref:eventicle_eventiclejs_SagaInstance_class.adoc[SagaInstance]&lt;TimeoutNames, InstanceData&gt;) =&gt; Promise&lt;void&gt;
|the async function to execute.

s|Returns
m|xref:eventicle_eventiclejs_Saga_class.adoc[Saga]&lt;TimeoutNames, InstanceData&gt;
|
|===

.Signature
[source,typescript]
----
onTimer(name: TimeoutNames, handle: (saga: SagaInstance<TimeoutNames, InstanceData>) => Promise<void>): Saga<TimeoutNames, InstanceData>;
----

========
[id="eventicle_eventiclejs_Saga_parallelEvents_member_1"]
=== parallelEvents(val)

========





.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|val
m|number
|

s|Returns
m|xref:eventicle_eventiclejs_Saga_class.adoc[Saga]&lt;TimeoutNames, InstanceData&gt;
|
|===

.Signature
[source,typescript]
----
parallelEvents(val: number): Saga<TimeoutNames, InstanceData>;
----

========
[id="eventicle_eventiclejs_Saga_startOn_member_1"]
=== startOn(eventName, config, handler)

========

Registers an event handler that can start new saga instances.

When the specified event type is received and no existing saga instance matches, a new saga instance will be created and the handler called. Only one startOn handler per event type is allowed.



.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|eventName
m|string
|The event type that can start new saga instances

m|config
m|\~StartHandlerConfig&lt;T, InstanceData, TimeoutNames&gt;
|Configuration for instance creation

m|handler
m|(saga: xref:eventicle_eventiclejs_SagaInstance_class.adoc[SagaInstance]&lt;TimeoutNames, InstanceData&gt;, event: T) =&gt; Promise&lt;void&gt;
|The function to execute when starting a new instance

s|Returns
m|xref:eventicle_eventiclejs_Saga_class.adoc[Saga]&lt;TimeoutNames, InstanceData&gt;
|
|===

.Signature
[source,typescript]
----
startOn<T extends EventicleEvent>(eventName: string, config: StartHandlerConfig<T, InstanceData, TimeoutNames>, handler: (saga: SagaInstance<TimeoutNames, InstanceData>, event: T) => Promise<void>): Saga<TimeoutNames, InstanceData>;
----

========
[id="eventicle_eventiclejs_Saga_subscribeStreams_member_1"]
=== subscribeStreams(streams)

========





.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|streams
m|string[]
|

s|Returns
m|xref:eventicle_eventiclejs_Saga_class.adoc[Saga]&lt;TimeoutNames, InstanceData&gt;
|
|===

.Signature
[source,typescript]
----
subscribeStreams(streams: string[]): Saga<TimeoutNames, InstanceData>;
----

========
