= class SagaInstance

Represents a single running instance of a saga workflow.

SagaInstance contains the runtime state and execution context for a specific saga execution. Each instance tracks its data, manages timers, and provides methods for saga lifecycle management.

 TimeoutNames - Union type of timer names this saga can schedule  T - Type of the saga's persistent data



== Properties

[id="eventicle_eventiclejs_SagaInstance_internalData_member"]
=== internalData

========






.Signature
[source,typescript]
----
readonly internalData: any;
----

========
[id="eventicle_eventiclejs_SagaInstance_record_member"]
=== record

========






.Signature
[source,typescript]
----
readonly record?: Record;
----

========
[id="eventicle_eventiclejs_SagaInstance_timersToAdd_member"]
=== timersToAdd

========

Timers pending addition in the next persistence cycle




.Signature
[source,typescript]
----
readonly timersToAdd: {
        name: TimeoutNames;
        config: {
            isCron: true;
            crontab: string;
        } | {
            isCron: false;
            timeout: number;
        };
    }[];
----

========
[id="eventicle_eventiclejs_SagaInstance_timersToRemove_member"]
=== timersToRemove

========

Timers pending removal in the next persistence cycle




.Signature
[source,typescript]
----
readonly timersToRemove: TimeoutNames[];
----

========

== Constructors

[id="eventicle_eventiclejs_SagaInstance_constructor_1"]
=== (constructor)(internalData, record)

========

Constructs a new instance of the `SagaInstance` class



.Parameters
[%header,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|internalData
m|any
|

m|record
m|Record
|
|===

.Signature
[source,typescript]
----
constructor(internalData: any, record?: Record);
----

========

== Methods

[id="eventicle_eventiclejs_SagaInstance_endSaga_member_1"]
=== endSaga(preserveInstanceData)

========

Marks the saga instance as completed and schedules it for cleanup.

Once a saga is ended, it will not receive any more events or timer callbacks. The instance data can optionally be preserved for debugging or audit purposes.



.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|preserveInstanceData
m|boolean
|Whether to keep instance data after completion

s|Returns
m|void
|
|===

.Signature
[source,typescript]
----
endSaga(preserveInstanceData?: boolean): void;
----

========
[id="eventicle_eventiclejs_SagaInstance_get_member_1"]
=== get(name)

========

Retrieves a piece of data from the saga instance state.



.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|name
m|K
|The key of the data to retrieve

s|Returns
m|T[K]
|The value associated with the key
|===

.Signature
[source,typescript]
----
get<K extends keyof T>(name: K): T[K];
----

========
[id="eventicle_eventiclejs_SagaInstance_lastEvent_member_1"]
=== lastEvent()

========






.Signature
[source,typescript]
----
lastEvent(): EventicleEvent;
----

========
[id="eventicle_eventiclejs_SagaInstance_removeTimer_member_1"]
=== removeTimer(name)

========





.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|name
m|TimeoutNames
|

s|Returns
m|void
|
|===

.Signature
[source,typescript]
----
removeTimer(name: TimeoutNames): void;
----

========
[id="eventicle_eventiclejs_SagaInstance_set_member_1"]
=== set(name, value)

========

Sets a piece of data in the saga instance state.

The value must be JSON-serializable as saga state is persisted. The 'id' field is protected and cannot be modified.



.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|name
m|keyof T
|The key to set

m|value
m|any
|The value to store (must be JSON-serializable)

s|Returns
m|void
|
|===

.Signature
[source,typescript]
----
set(name: keyof T, value: any): void;
----

========
[id="eventicle_eventiclejs_SagaInstance_upsertTimer_member_1"]
=== upsertTimer(name, config)

========

Create (or overwrite) a timer to call. Can be either a simple timer (millis to wait), or a cron timer.

If the timer is no longer wanted, it must be removed by calling



.Parameters
[%header%footer,cols="2,3,4",caption=""]
|===
|Name |Type |Description

m|name
m|TimeoutNames
|The timer to call

m|config
m|{
        isCron: true;
        crontab: string;
    } \| {
        isCron: false;
        timeout: number;
    }
|

s|Returns
m|void
|
|===

.Signature
[source,typescript]
----
upsertTimer(name: TimeoutNames, config: {
        isCron: true;
        crontab: string;
    } | {
        isCron: false;
        timeout: number;
    }): void;
----

========
