:source-highlighter: highlight.js

= Book Of Eventicle

== Intro

what is an event based system?

what is DDD?

== Quick Start

.Install
[source,bash]
----
yarn add @eventicle/eventiclejs
----

.Configure Eventicle

[source,typescript]
----
include::app/src/config.ts[tags=deps;config]
----

.Observe an event
_Treat an event stream as a simple Topic, do not request any historical data._

[source,typescript]
----
include::app/src/config.ts[tags=observe]
----

.Emit an event
_Emit an event to a stream, all following Eventicle event machinery is built on this_

[source,typescript]
----
include::app/src/config.ts[tags=emit]
----
<1> The event payload

.Fully replay an event stream
_This starts at the beginning of stream `app.streamname`, and will receive all historical events, then finish.
_Mostly used for offline, batch or automation actions, such as a view upgrade or full stream schema update_

[source,typescript]
----
include::app/src/config.ts[tags=replay]
----

.Fully replay an event stream and continue to observe
_This starts at the beginning of stream `app.streamname`, and will receive all historical events. It will then continue
to observe the stream._
_Used for most runtime stream consumption_

[source,typescript]
----
include::app/src/config.ts[tags=replay]
----

=== Next ...

Now you've seen the basics of an event based system, the creation and observation of events, you can start to
add in more conceptual pieces.

* _Views_, a way to process streams of events into data structures that can be queried efficiently.
* _Aggregate Roots_, components that store state, generate events, and enforce rules about how they relate to each other.
* _Commands_, components that record changes to the system by taking events and emitting them to streams.
* _Sagas_, event driven workflows. Implementing asynchronous business logic and integration with external systems in a way that safely isolates
them from your core application logic.

=== Internals: Event Client

consumer groups

=== Internals: Datastore

== Querying Data: Views

An event View is a component that observes event streams and applies a _Reducer_ function to them to generate a data structure
that is suitable for querying.

.An example View: Users
Create a list of users from `user.created` events and provider operations for users.
[source,typescript]
----
include::app/src/view-1.ts[]
----
<1> The consumer group is the same as for Redis Streams/ Kafka. Multiple view instances across processes will share processing.
<2> 1..n streams to subscribe to.
<3> View must handle all the potential event types in the stream. Normally this is done by picking out the required types and ignoring any others.
<4> An operation on a view does not have to be a simple query, it can be more advanced, as with a login check. It does though, always have to be read only to preserve the 1 way data flow semantics of the system
<5> A simple select all query on the view data structure.
<6> Register the view with Eventicle for it to attach the streams to the view.  Maintain a reference to it for your use to query the view data.
<7> View will have the user record when this event has been async processed.

=== In Memory Views

The persisted nature of event streams means that you can use the event stream as the system persistence Then have your views
be purely in memory. This means that they will rebuild each time the application starts, but will require no external data storage.

.An example View: Count of Users
Count the user registrations.
[source,typescript]
----
include::app/src/view-memory.ts[]
----
<1> Set the consumer group to be random. This means this instance will fully replay every time it connects to the event stream, and will receive all events, not share with other instances.
<2> The view state, in this case as simple integer count.
<3> Implement eventual consistency of the user counter via the event stream reducer in this view.
<4> Will output `1`, showing that the view observed the event that was emitted before it was connected, due to the full replay of the stream.
<5> Eventicle will connect the view to the requested event streams.

== Managing Local State: Domain Entities and Aggregate Roots

[mermaid]
....
graph TD
  A[Christmas] -->|Get money| B(Go shopping)
  B --> C{Let me think}
  C -->|One| D[Laptop]
  C -->|Two| E[iPhonesss]
  C -->|Three| F[fa:fa-car Car]

....


event sourcing

observing and waiting for async state changes in an AR with observationAdapter

== Changing Global State: Commands

An Eventicle command is responsible for mutating state and notifying the rest of the system about the state change via
one or more events on the shared event streams.


== Complex Interaction: Sagas and Workflows

== Local Data: The Datastore

== Idiomatic APIs that use Eventicle

==== Aggregate Root Event Observation Adapter

== Testing Eventicle Components and Systems

Testing event systems is essential, as their interactions are asynchronous and oftentimes with an implicit, or "choreographed" behaviour.

Eventicle is designed to be easy to test, and each type of component has an idiomatic approach for testing it.



==== consumeFullEventLog - Check event stream consistency

A common requirement when building event log based systems is to ensure that once an operation or workflow has completed,
that the log is in an expected consistent state.

This can be verified in testing using the `consumeFullEventLog` function.

[source, typescript]
----
// ... perform an operation/ workflow that emit events
let events = await consumeFullEventLog("user")

// verify that the event types we expect are in the log, in the right order, and there aren't any extra events
// or duplicates present, here with Jest expectations. Insert assertion library of your choice.

expect(events.map(value => value.type)).toStrictEqual([
  "user.created",
  "user.password_set",
  "user.approved",
  "user.account_locked",
]);
----



=== Unit Tests: Commands

=== Unit Tests: Aggregate Roots

=== Unit Tests: Sagas

=== Integration Tests

== Designing Eventicle Event Systems

Event Storm
Design Happy Path workflows

Derive Desired Interactions.
* Sagas should exist as their own logical entity, no matter their physical location.

== Monitoring

=== APM
_Support for distributed tracing is experimental, and the API is subject to change_

Distributed Tracing is a very useful tool for monitoring system health and diagnosing issues in distributed systems.

Eventicle is event based, which poses some challenges to implementing distributed tracing, which normally assumes
that a transaction is RPC based and forms a tree structure in its interactions.

Event based systems do not generally form an interaction tree, instead they form a graph structure that when visualised will
give overlapping concepts of a "transaction".

Given that, distributed tracing is not universally useful in an Eventicle system in the way that it is in an HTTP/ RPC system.

It is most useful when you use it from the point of view of your API layer, and use it to trace interactions that relate to that API.

This is supported in Eventicle, via the `ApmApi` object.

Currently, only Elastic APM is supported, and can be enabled like so

```
// at the start of your index file, before any imports, to enable the agent to instrument correctly.
const apm = require('elastic-apm-node').start({
    serviceName: 'my-cool-service'
  });

import {apm as eventicleApm} from "@eventicle/eventiclejs";

eventicleApm.setEventicleApm(eventicleApm.elasticApmEventicle(apm))

```

This will generate APM spans (and transactions) using the underlying API, and attach trace information to events. Transmitting
that information across transports is specific to the transport.  The codec will also need to ensure that it
collects that information and recreates it appropriately.

The default `EventClientJsonCodec` and both the `eventClientOnDatastore` and `eventClientOnKafka` support distributed trace headers.
`EventClientJsonCodec` currently sets trace headers compatible with Elastic APM.

When loaded, the following tracing will occur :-

* Each Command execution will exist in a span and have the type `Command`
* Saga steps will exist in individual transactions/ spans, and will have the type `SagaStep`. They will join the transaction that
create the source event, if the information exists.

=== Gathering Metrics

The highly asynchronous nature of Event systems requires different monitoring.  Eventicle gathers some metrics for you to aid in this.

Eventicle will automatically gather runtime metrics for the following :-

* View event latency, latest value.
* Adapter event latency, latest value.
* Saga event latency (for each event step), latest value.

These are all lazily created, and so the metric will only exist if the view/ adapter/ saga has received an event.

They can be obtained like so

[source, typescript]
----
import {metrics} from "@eventicle/eventiclejs";

let metricDoc = metrics()
console.log(metricDoc)

{
"view-latency":
   {
      "user-view": {
         "latest": 40,           <1>
         "user.created": 40      <2>
      },
      "user-view-v2":{
          "latest": 4403371,      <3>
          "user.created": 4403371,
          "user.delete": 440971,
      },
    },
"saga-latency" : { .. as above },
"adapter-latency" : { .. as above }
}

----
<1> A view, with the consumer group "user-view". This view has a low latency and appears to be running well.
<2> The individual event types that the view has received are given their own latency, plus the last event received in the "latest" property.
<3> This view has very high latencies, and is most likely performing a historical replay.

Care needs to be taken during initial View creation, as they will perform a full event replay of their streams, and so
will start to show latency metrics for the event they are currently at.   This will rapidly change as they replay the stream,
but may start far in the past and so will show excessively high apparent latencies.

Once the view has come up to near current, latencies will be reasonable and can be used to monitor view consistency health.
This will only be true if events are still being produced as the view is replaying. If the view is only replaying historical data,
then the latency will continue to show the time from the last event createdAt time and the time the view processed the event.

Metrics do not persist beyond application restart.

Latency metrics should be used to monitor if one of the above components is processing events too slowly and is falling behind.

They should not be used to understand if a view/ saga is "up to date". This is conceptually difficult in an eventually consistent, as there
is no globally consistent view of what "up to date" or "current" actually is.

If you wish to know if a view is consistent with some action, structure your view such that it can answer if it has
successfully processed the event(s) that were created by the action. This gives you a specific form of consistency check
that is straightforward to implement.

=== Event Client: Using with Kafka

=== Event Client: Transport Event Encoding

=== Improving Use of Typescript Types When Using Events



